-keep class com.google.api.** { *; }
-keep class com.google.http.** { *; }
-dontwarn com.google.api.**
-dontwarn org.apache.**
-dontwarn com.sun.**
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class okhttp3.** { *; }
